### ISSUE TITLE
Multiple components being loaded

### ISSUE THREAD

**Issue by threeaccents** [ionic-team/stencil-router#66] opened 2018-08-20 23:03 UTC
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.11.0
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Given these routes:
```html
<stencil-route url='/enviroment/new' component='create-enviroment-view' />
<stencil-route url='/enviroment/:id' component='enviroment-details-view' />
```
And a user visits the URL `/enviroment/new` the correct view is rendered; however the `enviroment-details-view` componentWillLoad will load method still gets called.  

**Expected behavior:**

`enviroment-details-view` should not be instantiated.

**Steps to reproduce:**

**Related code:**

```
I think the above code shows it all.
```

**Other information:**

**Comment by jthoms1** [comment] 2018-08-21 18:48
Technically both routes match.  Are you using a `stencil-router-switch` around this bit of code?  If not you probably should to ensure that the first match is the only one that renders.

https://github.com/ionic-team/stencil-router/wiki/stencil-route-switch

**Comment by threeaccents** [comment] 2018-08-22 17:02
Yea I'm using `stencil-router-switch`. 

```html
<stencil-router>
    <stencil-route-switch scrollTopOffset={0}>
        <stencil-route url='/enviroment/new' component='create-enviroment-view' />
        <stencil-route url='/enviroment/:id' component='enviroment-details-view' />
    </stencil-route-switch>
</stencil-router>
```

Both routes do match but shouldn't it just be the first route that matches the one that gets loaded and called?

**Comment by jthoms1** [comment] 2018-08-30 17:02
I will add some tests to verify this. Thanks!

**Comment by jthoms1** [comment] 2018-08-31 20:59
Sorry forgot to answer.  Under a switch statment the first match should respond.  In this case `environment-details-view` should not appear in the dom and an instance should not be created.

I am actually unable to reproduce, do you think you could provide a test repo with this issue. Thanks!

**Comment by threeaccents** [comment] 2018-09-03 16:13
Hey man I made a new repo replicating the bug. https://gitlab.com/rodzzlessa24/stencil-router-bug

As you can see I just created a new component `new-profile` and added it to the routes.

```html
          <stencil-router>
            <stencil-route-switch scrollTopOffset={0}>
              <stencil-route url='/' component='app-home' exact={true} />
              <stencil-route url='/profile/new' component='new-profile' exact={true} />
              <stencil-route url='/profile/:name' component='app-profile' />
            </stencil-route-switch>
          </stencil-router>
```

I added a `console.log` in the `componentWillLoad` function of the `app-profile` component. If you visit `/profile/new` you'll see the log message from `app-profile` will also be logged.

**Comment by threeaccents** [comment] 2018-09-03 18:35
I think the issue might only occur on page refreshes if I go to the route using a `<stencil-route-link>` then there's no issue.

**Comment by jthoms1** [comment] 2018-09-04 12:50
Thanks for the repo. I am able to reproduce and have identified a fix. Will be releasing a new version today.

**Comment by jthoms1** [comment] 2018-09-21 14:53
This was fixed in release 0.2.7. Thanks!

**Closed** 2018-09-21 14:54 UTC
Labels: bug

**Comment by threeaccents** [comment] 2018-09-24 17:14
Hey man I tried updating to 0.2.7; however its causing issues with the compiler. I opened an issue in the stencil core repo. https://github.com/ionic-team/stencil/issues/1106

**Comment by jthoms1** [comment] 2018-09-24 18:03
There was an issue with 0.2.7. Please use 0.2.8. 🤦‍♂️
