### ISSUE TITLE
Redirect to a 404 component If route not found

### ISSUE THREAD

**Issue by ansarizafar** [ionic-team/stencil-router#25] opened 2017-11-18 14:44 UTC
Provide a feature to define a 404 route component.

**Comment by jthoms1** [comment] 2017-12-18 19:52
I believe we will be adding a switch component that will allow you to set a default route which would accommodate for a 404.  You can see how this would work from react-router. https://reacttraining.com/react-router/web/example/no-match

**Comment by jgw96** [comment] 2018-02-19 15:54
Going to close this as a duplicate of https://github.com/ionic-team/stencil-router/issues/22 since that feature will provide this functionality. Thanks for using Stencil!

**Closed by jgw96** 2018-02-19 15:54 UTC
