### ISSUE TITLE
group required when using wildcards

### ISSUE THREAD

**Issue by relvao** [ionic-team/stencil-router#20] opened 2017-11-01 17:18 UTC
This router example seems to work as expected. If the route is not /home it shows not-found-page. 
```
<stencil-router>
  <stencil-route url="/home" component="home-page" exact={true} group="base" />
  <stencil-route url="/*" component="not-found-page" group="base" />
</stencil-router>
```

but if you remove the group attribute, not-found-page shows for any route, including the home page. Is this the desired behaviour?

**Comment by jthoms1** [comment] 2017-12-18 20:04
I plan on adding a switch component that will allow you to group for not found pages.  We have a way to accomplish this today with groups but the syntax is less than desirable. https://github.com/ionic-team/stencil-router/blob/ea3a8d526255ad2ad1fe3dc4f70048a9c220486b/src/components/__tests__/test-demo-six.tsx#L16

**Comment by jgw96** [comment] 2018-02-19 15:56
Closing this as a duplicate of https://github.com/ionic-team/stencil-router/issues/22 since that feature will provide this functionality. Thanks for using Stencil!

**Closed by jgw96** 2018-02-19 15:56 UTC
