### ISSUE TITLE
Runtime error detected during componentWillLoad(): stencil-router

### ISSUE THREAD

**Issue by jagreehal** [ionic-team/stencil-router#55] opened 2018-06-10 19:22 UTC
I have tried to update the ssr example to the latest version (https://github.com/jagreehal/stencil-ssr-starter) but when refreshing the page I get the error:

[ ERROR ]  Runtime error detected during componentWillLoad(): stencil-router
           Cannot read property '_history' of null TypeError: Cannot read property '_history' of null at Window.get
           history [as history]

**Comment by jthoms1** [comment] 2018-08-02 13:42
Could you run the following command in your project root? `npm ls --depth=0` and comment on the output. Thanks!

**Comment by jthoms1** [comment] 2018-08-08 16:46
closing this as a duplicate of #36

**Closed by jthoms1** 2018-08-08 16:46 UTC
