### ISSUE TITLE
Default/Home page always rendered with SSR

### ISSUE THREAD

**Issue by ihadeed** [ionic-team/stencil-router#7] opened 2017-09-01 09:52 UTC
Not sure if this is related to [@stencil/router](https://github.com/ionic-team/stencil-router) or [@stencil/core](https://github.com/ionic-team/stencil).
 
The default/home page (that handles the `/` path) is always being rendered with server-side rendering. This happens even if I set `exact` to `true`. 

Expected behaviour: 
Router should render a single route that matches the URL.

Current behaviour:
Router is rendering the default route, as well as the route that matches the URL.

To reproduce this issue, you can clone any of these repos, build the app, then run `node server.js`: 
- https://github.com/ionic-team/stencil-starter-ssr
- https://github.com/ihadeed/stencil-site/tree/ssr (`ssr` branch)

**Comment by kylecordes** [comment] 2017-09-03 01:58
I think I am seeing this also. Took a few minutes of wondering why two routes appear, to figure out one comes from SSR. Incidentally, that one doesn't get its `componentProps`.

**Comment by ihadeed** [comment] 2017-09-03 02:20
My guess: the home page always shows up because it's pre-rendered when running `stencil build`. The server-side renderer then takes that page and renders the router contents again.

**Comment by marvinhagemeister** [comment] 2017-09-03 07:33
@ihadeed can confirm that this is due to SSR. When replacing `www/index.html` with the one from `src/` the duplicate components are gone.

**Comment by marvinhagemeister** [comment] 2017-09-05 16:08
Just upgraded all stencil-related dependencies to the most recent version (`@next`) and the issue is gone for me. Seems like something in `@stencil/core` fixed this issue.

**Comment by kylecordes** [comment] 2017-09-05 18:42
It appears to be fixed for me also. I didn't do a standalone test, but I was able to remove a workaround from my example app:

https://github.com/kylecordes/stencil-todomvc/commit/43b7db45f1cd5b713fcaabd66da822f4ded4c443

**Comment by jthoms1** [comment] 2017-09-05 20:49
Yes this was an issue in @stencil/core. It was fixed with ionic-team/stencil@9839cafa347077d9ab62bffa14663c4b4f7b9bdf

**Closed by jthoms1** 2017-09-05 20:49 UTC
