### ISSUE TITLE
Stencil config includes demos

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil-router#12] opened 2017-09-26 14:32 UTC
Am I correct in thinking the config shouldn't include our demos?

https://github.com/ionic-team/stencil-router/blob/master/stencil.config.js

**Comment by jthoms1** [comment] 2017-10-04 14:35
Ya, unfortunately not an easy way to setup test demos in this repo without including them in the stencil config.

**Comment by chrisweight** [comment] 2018-01-30 13:12
Confirmed this, it's currently breaking tests unfortunately as it looks like the test-demo components are included in the `collection-manifest.json` in dist on compile

```
   {
      "components": [
        "test-app"
      ]
    },
    {
      "components": [
        "test-demo-four"
      ]
    },
    {
      "components": [
        "test-demo-six"
      ]
    },
    {
      "components": [
        "test-demo-three"
      ]
    }
```

**Comment by chrisweight** [comment] 2018-01-30 13:13
If I make `generateDistribution: false` in `stencil.config.js` this ^^ obviously doesn't happen ...

**Comment by jgw96** [comment] 2018-02-19 16:15
Closing this as the demo components do not seem to be included in the config anymore. Thanks!

**Closed by jgw96** 2018-02-19 16:15 UTC
